[project]
name = "selenium-remote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "pymysql>=1.1.1",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "selenium>=4.27.1",
]
